disabled_rules:
  #- enable_autolayout
  #- duplicate_constraint
  #- duplicate_id
  #- custom_module
  #- ambiguous

enabled_rules:
  #- custom_class_name # ファイル名は末尾の `ViewController` を省略したいため
  - relative_to_margin
  - misplaced
  #- storyboard_viewcontroller_id # IDは末尾の `ViewController` を省略したいため
  - stackview_backgroundcolor
  - image_resources
  - use_base_class
  - view_as_device
  - reuse_identifier
  - color_resources
  - use_trait_collections
  #- hides_bottom_bar # [Hide Bottom Bar on Push]はデフォルトOFFのため

included:
  - Shared
  - UhooiPicBook
  - UhooiPicBookStickers
  - UhooiPicBookWidgets
  - UhooiPicBookWidgetsConfigurableIntent
  - UhooiPicBookTests
  - UhooiPicBookUITests
  - Sources
  - Tests

excluded:
  - SourcePackages
  - Tools
  - Generated

view_as_device_rule:
  device_id: retina6_1 # iPhone 11

