parent_config: https://raw.githubusercontent.com/uhooi/SwiftLint-Config/v1.13.0/uhooi-base-swiftlint-config.yml

included:
  - Shared
  - UhooiPicBook
  - UhooiPicBookStickers
  - UhooiPicBookWidgets
  - UhooiPicBookWidgetsConfigurableIntent
  - Sources

excluded:
  - UhooiPicBookTests
  - UhooiPicBookUITests
  - Tests
  - SourcePackages
  - Tools
  - Generated

