parent_config: https://raw.githubusercontent.com/uhooi/SwiftLint-Config/v1.9.0/uhooi-base-swiftlint-config.yml

disabled_rules:
  - missing_docs

included:
  - Shared
  - UhooiPicBook
  - UhooiPicBookStickers
  - UhooiPicBookWidgets
  - UhooiPicBookWidgetsConfigurableIntent
  - Sources

excluded:
  - UhooiPicBookTests
  - UhooiPicBookUITests
  - Tests
  - SourcePackages
  - Tools
  - Generated

