parent_config: https://raw.githubusercontent.com/uhooi/SwiftLint-Config/v1.10.0/uhooi-base-swiftlint-config.yml

disabled_rules:
  - missing_docs

custom_rules:
  if_let_shorthand:
    included: 
      - ".*\\.swift"
    name: "`if let` shorthand for shadowing an existing optional variable"
    regex: '(if|guard)\s+let\s+(.+?)\s*=\s*(\2)'
    message: "Use `if let` shorthand."
    severity: warning

included:
  - Shared
  - UhooiPicBook
  - UhooiPicBookStickers
  - UhooiPicBookWidgets
  - UhooiPicBookWidgetsConfigurableIntent
  - Sources

excluded:
  - UhooiPicBookTests
  - UhooiPicBookUITests
  - Tests
  - SourcePackages
  - Tools
  - Generated

