name: UhooiPicBook

options:
  bundleIdPrefix: com.theuhooi
  deploymentTarget:
    iOS: 13.0
  carthageExecutablePath: mint run Carthage/Carthage carthage

settings:
  configs:
    debug:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"

targets:
  UhooiPicBook:
    type: application
    platform: iOS
    sources:
      - UhooiPicBook
      - path: "UhooiPicBook/Generated/MockResults.swift"
        optional: true
        type: file
      - path: "UhooiPicBook/Generated/R.generated.swift"
        optional: true
        type: file
    settings:
      base:
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: 47E56DYP3N
        INFOPLIST_FILE: UhooiPicBook/Info.plist
        OTHER_LDFLAGS: $(inherited) $(OTHER_LDFLAGS) -ObjC
    dependencies:
      - framework: Carthage/Build/iOS/Firebase.framework
        embed: false
        link: false
      - framework: Carthage/Build/iOS/abseil.framework
        embed: false
      - framework: Carthage/Build/iOS/BoringSSL-GRPC.framework
        embed: false
      - framework: Carthage/Build/iOS/FIRAnalyticsConnector.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseABTesting.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseAnalytics.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseCore.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseCoreDiagnostics.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseCrashlytics.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseFirestore.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseInstallations.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseInstanceID.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebasePerformance.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseRemoteConfig.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleAppMeasurement.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleDataTransport.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleDataTransportCCTSupport.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleToolboxForMac.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleUtilities.framework
        embed: false
      - framework: Carthage/Build/iOS/gRPC-C++.framework
        embed: false
      - framework: Carthage/Build/iOS/gRPC-Core.framework
        embed: false
      - framework: Carthage/Build/iOS/GTMSessionFetcher.framework
        embed: false
      - framework: Carthage/Build/iOS/leveldb-library.framework
        embed: false
      - framework: Carthage/Build/iOS/nanopb.framework
        embed: false
      - framework: Carthage/Build/iOS/PromisesObjC.framework
        embed: false
      - framework: Carthage/Build/iOS/Protobuf.framework
        embed: false
    preBuildScripts:
      - script: |
                "$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/$TARGET_NAME/Generated/R.generated.swift"
        name: Generate Resources with R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/$TARGET_NAME/Generated/R.generated.swift
      - script: |
                if which mint >/dev/null; then
                  rm -f $SRCROOT/$TARGET_NAME/Generated/MockResults.swift
                  mint run mockolo mockolo --sourcedirs $SRCROOT/$TARGET_NAME --destination $SRCROOT/$TARGET_NAME/Generated/MockResults.swift
                else
                  echo "warning: Mint not installed, download from https://github.com/yonaskolb/Mint"
                fi
        name: Generate Mocks with Mockolo
        outputFiles:
          - $SRCROOT/$TARGET_NAME/Generated/MockResults.swift
    postCompileScripts:
      - script: |
                if which mint >/dev/null; then
                  mint run swiftlint swiftlint autocorrect --format
                  mint run swiftlint swiftlint
                else
                  echo "warning: Mint not installed, download from https://github.com/yonaskolb/Mint"
                fi
        name: Run SwiftLint
      - script: |
                if ! which mint >/dev/null; then
                  echo "warning: Mint not installed, download from https://github.com/yonaskolb/Mint"
                  exit 0
                fi

                git_path=/usr/local/bin/git
                files=$($git_path diff --diff-filter=d --name-only -- "*.swift" "*.h" "*.m")
                if (test -z $files) || (test ${#files[@]} -eq 0); then
                  echo "no files changed."
                  exit 0
                fi

                options=""
                for file in $files
                do
                  options="$options $SRCROOT/$file"
                done

                mint run SpellChecker SpellChecker --yml $SRCROOT/spell-checker.yml -- $options
        name: Run SpellChecker
    postBuildScripts:
      - script: /bin/sh ./Scripts/FirebaseCrashlytics/run
        name: Run Firebase Crashlytics
        inputFiles:
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)

  UhooiPicBookTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - UhooiPicBookTests
    settings:
      base:
        INFOPLIST_FILE: UhooiPicBookTests/Info.plist
    dependencies:
      - target: UhooiPicBook

  UhooiPicBookUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - UhooiPicBookUITests
    settings:
      base:
        INFOPLIST_FILE: UhooiPicBookUITests/Info.plist
    dependencies:
      - target: UhooiPicBook

schemes:
  UhooiPicBook:
    build:
      targets:
        UhooiPicBook: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - UhooiPicBook
      targets:
        - name: UhooiPicBookTests
          parallelizable: true
          randomExecutionOrder: true
        - name: UhooiPicBookUITests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

