on:
  issues:
    types:
      - opened

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v1
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })

  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v1
        with:
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Triage']
            })

